# -*- coding: utf-8 -*-
"""upload_logs_to_yadisk_yadisklib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TN-qW3SE3HPRPz5ms1QfdmSrgec3sF_Y
"""

import yadisk
import pandas as pd

# Настройки путей
LOCAL_CSV_PATH = "data/log.csv"
XLSX_PATH = "data/log.xlsx"
REMOTE_PATH = "/log.xlsx"

# OAuth-токен
OAUTH_TOKEN = "y0__xCtwfykqveAAhjWljcg1O2f8RICGIMXA9vRn5dN-6GzVa8qQOVVkw"

# Авторизация
y = yadisk.YaDisk(token=OAUTH_TOKEN)

# Проверка авторизации
if not y.check_token():
    raise Exception("Токен недействителен. Проверь значение.")

# Конвертация CSV в XLSX
df = pd.read_csv(LOCAL_CSV_PATH)
df["timestamp"] = pd.to_datetime(df["timestamp"]).dt.strftime("%Y-%m-%d %H:%M:%>
df.to_excel(XLSX_PATH, index=False)

# Загрузка на Диск
with open(XLSX_PATH, "rb") as f:
    y.upload(f, REMOTE_PATH, overwrite=True)

print("Файл успешно загружен на Яндекс.Диск!")